.\" RCSID @(#)$Id: istext.man,v 1.1 1998/10/07 16:19:56 rk Exp $
.\" LIBDIR
.TH "ISTEXT" "3rko" "21 May 1998"
.SH NAME
istext \- returns 0 or 1 if the character is a text character
.SH SYNOPSIS

 #include "librko.h"
 int istext(int c);

.SH DESCRIPTION
.I istext
returns 1 if the character
.I c
is a text character with character values 7-13,27,32-126;
the special characters recognized by C, the escape character, and
the usual ASCII printable characters.
.P
The value for
.I c
should be within the range [0-255], else
.I istext
will mask out the upper bits.

.SH SEE ALSO
ascii(7),isascii(3),isalpha(3), etc.

.SH DIAGNOSTICS
none

.SH AUTHOR
R.K.Owen,Ph.D.

.KEY WORDS
