#!/bin/sh -f
cat > librko.man <<!
.\" USMID %W%
.\" RCSID @(#)$Id: Librko.man,v 1.1 1998/10/07 16:19:56 rk Exp $
.TH "LIBRKO" "3rko" "12 May 1995"
.SH NAME
librko \- an eclectic collection of C functions developed by R.K.Owen,Ph.D.
.SH SYNOPSIS

 #include "librko.h"

.SH DESCRIPTION
.I librko
is an eclectic collection of C routines/functions created by R.K.Owen,Ph.D.
for C programming.  They are written in ISO Standard C / POSIX and should
be very portable.  An ANSI-C compiler is a must.

.SH SEE ALSO
.RS -.5
.nf
!
./what2man >> librko.man
cat >> librko.man <<!
.fi
.RE

.SH AUTHOR
R.K.Owen,Ph.D.

.KEY WORDS
!
